### ISSUE TITLE
Duckstation/Duckstation-preview are showing only nightly as the latest version

### ISSUE THREAD

**Issue by ppvnf** [hermanjustnu/scoop-emulators#80]
is this correct or there's something broken with these manifests?
https://github.com/hermanjustnu/scoop-emulators/commit/81a1893b527cf74b92f5c3da3e17fcfb0766f800
https://github.com/hermanjustnu/scoop-emulators/commit/d7df39ab276c1f777d86c77e4851d81f36565131
Why the checkver was removed?

**Comment by ppvnf** [comment]
Maybe it has something to do with the fact that there are now 3 duckstation versions:
https://github.com/stenzek/duckstation/releases/tag/preview
https://github.com/stenzek/duckstation/releases/tag/latest
https://github.com/stenzek/duckstation/releases/tag/legacy

**Comment by hermanjustnu** [comment]
Since https://github.com/ScoopInstaller/Scoop/pull/5166 was included in [0.3.1](https://github.com/ScoopInstaller/Scoop/pull/5247), nightlies can now be updated using `scoop update <manifest>|*`. Or by forcing an update with `-f`.

**Comment by ppvnf** [comment]
Okay, I am gonna try that out!

**Comment by ppvnf** [comment]
I understand this approach for duckstation-preview, but regular Duckstation isn't really updated so often

**Comment by hermanjustnu** [comment]
Since the link is static, when regular Duckstation is updated the hash would be incorrect for a time perioid. I know this is not optimal, but maybe with https://github.com/ScoopInstaller/Scoop/issues/5266 in place, it will work a little better. Right now, a `scoop cleanup *` will take care of the duplicates downloads.
